name: calkulator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
    
  # youtube_player_flutter: ^9.1.2
  video_player: ^2.10.0
  

  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  firebase_performance: ^0.11.1

  flutter_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  hexcolor: ^3.0.1
  cupertino_icons: ^1.0.8
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.9.0


flutter:
  uses-material-design: true

  assets:
    - assets/